[tool.black]
line-length = 120
target-version = ["py39"]

[tool.isort]
profile = "black"
multi_line_output = 3
extend_skip = ["env/**", "venv/**", ".pytest_cache/**", ".venv/**"]
line_length = 120
skip_gitignore = true
